# Generated by Django 2.2 on 2020-11-17 14:02

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(default='header empty')),
                ('category', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients_Dine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=2180)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('money_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dine_app.Categories_Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=2180)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_number', models.IntegerField()),
                ('vacant', models.BooleanField(default=False)),
                ('square', django.contrib.gis.db.models.fields.PolygonField(srid=2180)),
                ('res_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dine_app.Restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('res_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dine_app.Restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='Orders_Dine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_amout', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment', models.BooleanField(default=True)),
                ('order_time', models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 17, 14, 2, 36, 808534, tzinfo=utc))),
                ('take_away', models.BooleanField(default=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dine_app.Clients_Dine')),
                ('foods_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dine_app.Food')),
            ],
        ),
        migrations.AddField(
            model_name='categories_menu',
            name='res_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dine_app.Restaurants'),
        ),
    ]
