# Generated by Django 2.2 on 2020-11-17 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_dine',
            name='order_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 17, 14, 5, 55, 367104, tzinfo=utc)),
        ),
    ]
