# Generated by Django 2.2 on 2020-11-19 11:14

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0002_auto_20201117_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('payment', models.BooleanField(default=True)),
                ('take_away', models.BooleanField(default=True)),
                ('money_amout', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('order_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('order_aproximate_time', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dine_app.Clients_Dine')),
                ('res_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dine_app.Restaurants')),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=True, size=None),
        ),
        migrations.DeleteModel(
            name='Orders_Dine',
        ),
    ]
