# Generated by Django 2.2 on 2020-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0003_auto_20201119_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_dine',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clients_dine',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
