# Generated by Django 2.2 on 2020-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0004_auto_20201126_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_dine',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
