# Generated by Django 2.2 on 2020-11-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0005_auto_20201126_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients_dine',
            name='id',
        ),
        migrations.AlterField(
            model_name='clients_dine',
            name='phone_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
