# Generated by Django 2.2 on 2020-12-04 13:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0006_auto_20201126_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='foods_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=True, size=None),
        ),
        migrations.AlterField(
            model_name='orders',
            name='money_amout',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
