# Generated by Django 2.2 on 2020-12-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0007_auto_20201204_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='client_id',
            new_name='cli_id',
        ),
    ]
