# Generated by Django 2.2 on 2020-12-07 16:38

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0008_auto_20201207_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='foods_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=True, size=None),
        ),
    ]
