# Generated by Django 2.2 on 2020-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0013_orders_cli_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_dine',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
