# Generated by Django 2.2 on 2020-12-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dine_app', '0014_auto_20201207_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cli_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dine_app.Clients_Dine'),
        ),
    ]
